name: Square Catalog Sync
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *' # 9:00 UTC daily (adjust if needed)

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Ensure deps are present (including the Square SDK), even if your lockfile doesn't list it yet
      - name: Install deps (ensure square is present)
        run: |
          npm ci || true
          npm ls square || npm i square@^41

      - name: Preflight (auth & URLs)
        env:
          SQUARE_ENVIRONMENT: ${{ vars.SQUARE_ENVIRONMENT }}
          SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}
          SQUARE_LOCATION_ID: ${{ vars.SQUARE_LOCATION_ID }}
          SQUARE_APP_ID: ${{ vars.SQUARE_APP_ID }}
        run: node scripts/preflight.mjs

      - name: Fetch Catalog -> data/products.json
        env:
          SQUARE_ENVIRONMENT: ${{ vars.SQUARE_ENVIRONMENT }}
          SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}
          SQUARE_LOCATION_ID: ${{ vars.SQUARE_LOCATION_ID }}
          OUTPUT_PATH: data/products.json
        run: node scripts/fetch-square.mjs

      - name: Commit & push catalog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/products.json
          git commit -m "chore: update Square catalog [skip ci]" || echo "No changes"
          git push
