name: Square → Catalog JSON

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci

      # Ensure the Square SDK is present (in case lockfile is old)
      - run: npm i square@^40

      - name: Run Square sync
        run: npm run sync:square
        env:
          SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}
          SQUARE_LOCATION_ID:  ${{ secrets.SQUARE_LOCATION_ID }}
          # Accept either variable name; prefer ENV, fall back inside the script
          SQUARE_ENVIRONMENT:  ${{ vars.SQUARE_ENVIRONMENT || 'production' }}
          OUTPUT_PATH:         data/products.json

      - name: Commit & push if changed
        run: |
          if ! git diff --quiet --exit-code data/products.json; then
            git config user.name  "square-sync[bot]"
            git config user.email "square-sync[bot]@users.noreply.github.com"
            git add data/products.json
            git commit -m "Square sync: refresh catalog JSON"
            git push
          else
            echo "No changes."
          fi
