diff --git a/.github/workflows/square-sync.yml b/.github/workflows/square-sync.yml
index 9699e00bdde53961b2a48d38fb53657ccdec6104..30573ceaa0cdf7e2e64a624accfd2cdeca4750be 100644
--- a/.github/workflows/square-sync.yml
+++ b/.github/workflows/square-sync.yml
@@ -65,51 +65,51 @@ jobs:
                 hashFiles( format('{0}/npm-shrinkwrap.json', steps.workdir.outputs.dir) ) == '' &&
                 hashFiles( format('{0}/yarn.lock', steps.workdir.outputs.dir) ) == '' }}
         uses: actions/setup-node@v4
         with:
           node-version: 20
 
       # Install deps: ci if lockfile present, else plain install
       - name: Install deps
         working-directory: ${{ steps.workdir.outputs.dir }}
         run: |
           if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
             npm ci
           else
             npm i --no-audit --no-fund
           fi
 
       - name: Node & NPM versions
         run: |
           node -v
           npm -v
 
       - name: Verify script and npm scripts
         working-directory: ${{ steps.workdir.outputs.dir }}
         run: |
           test -f scripts/fetch-square.js || { echo "::error::Missing scripts/fetch-square.js"; exit 1; }
-          node -e "try{const pj=require('./package.json'); console.log('package name:', pj.name); console.log('has script sync:square:', Boolean(pj.scripts && pj.scripts['sync:square']));}catch(e){console.error(e); process.exit(1)}"
+          node --input-type=module -e "import { readFileSync } from 'fs'; const pkg = JSON.parse(readFileSync(new URL('./package.json', import.meta.url))); console.log('package name:', pkg.name); console.log('has script sync:square:', Boolean(pkg.scripts && pkg.scripts['sync:square']));"
 
       - name: Run sync
         working-directory: ${{ steps.workdir.outputs.dir }}
         env:
           SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}
           SQUARE_ENV: ${{ secrets.SQUARE_ENV || 'production' }}
           SQUARE_LOCATION_ID: ${{ secrets.SQUARE_LOCATION_ID }}
         run: |
           npm run sync:square
 
       - name: Verify products.json
         working-directory: ${{ steps.workdir.outputs.dir }}
         run: |
           test -f data/products.json || { echo "::error::data/products.json was not created"; exit 1; }
           ls -lh data/products.json
           head -n 5 data/products.json || true
 
       # If your site is served from /docs but your workdir is root, copy over.
       - name: Move products.json to docs if site serves from /docs
         if: ${{ steps.workdir.outputs.dir == '.' && (hashFiles('docs/index.html') != '' || hashFiles('docs/index.htm') != '') }}
         run: |
           mkdir -p docs/data
           cp -f data/products.json docs/data/products.json
           ls -lh docs/data/products.json
 
