name: Square → Catalog JSON

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Prefer ci; if lock is stale, fall back to install once, then ci
      - name: Install deps
        run: |
          if npm ci; then
            echo "npm ci succeeded"
          else
            echo "npm ci failed; attempting npm install to refresh lockfile"
            npm install --no-audit --no-fund
            npm ci
          fi

      - name: Run Square sync
        run: npm run sync:square
        env:
          SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}
          SQUARE_LOCATION_ID:  ${{ secrets.SQUARE_LOCATION_ID }}
          SQUARE_ENVIRONMENT:  ${{ vars.SQUARE_ENVIRONMENT || 'production' }}
          OUTPUT_PATH:         data/products.json

      - name: Commit & push if changed
        run: |
          if ! git diff --quiet --exit-code data/products.json package-lock.json; then
            git config user.name  "square-sync[bot]"
            git config user.email "square-sync[bot]@users.noreply.github.com"
            git add data/products.json package-lock.json
            git commit -m "Square sync: refresh catalog JSON (and lockfile if needed)"
            git push
          else
            echo "No changes."
          fi
