name: Square Sync

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run without committing changes"
        required: false
        default: "false"
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours

permissions:
  contents: write

concurrency:
  group: square-sync-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}
      SQUARE_ENVIRONMENT: ${{ vars.SQUARE_ENVIRONMENT || 'production' }}
      SQUARE_LOCATION_ID: ${{ vars.SQUARE_LOCATION_ID }}
      OUTPUT_PATH: data/square-items.json

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Ensure Node project & install Square SDK
        run: |
          # Create package.json if the repo doesn't have one
          if [ ! -f package.json ]; then
            npm init -y
          fi
          # Ensure ESM so .mjs / import works cleanly
          npm pkg set type=module
          # Install/upgrade Square SDK (works for both new and legacy imports via square/legacy)
          npm install square@^40

      - name: Install deps (if the repo already had a package.json/lock)
        run: |
          if [ -f package-lock.json ]; then
            npm ci || npm install
          else
            npm install
          fi

      - name: Ensure output folder exists
        run: mkdir -p "$(dirname "${OUTPUT_PATH}")"

      - name: Run Square fetch script (supports ESM/CJS)
        run: |
          set -e
          if [ -f "fetch-square.js" ]; then
            # Respect your original filename; run as ESM if needed
            node --experimental-modules fetch-square.js --out "${OUTPUT_PATH}" || node fetch-square.mjs --out "${OUTPUT_PATH}" || true
            if [ ! -f "${OUTPUT_PATH}" ]; then
              cp fetch-square.js fetch-square.mjs
              node fetch-square.mjs --out "${OUTPUT_PATH}"
            fi
          elif [ -f "scripts/fetch-square.js" ]; then
            node --experimental-modules scripts/fetch-square.js --out "${OUTPUT_PATH}" || node scripts/fetch-square.mjs --out "${OUTPUT_PATH}" || true
            if [ ! -f "${OUTPUT_PATH}" ]; then
              cp scripts/fetch-square.js scripts/fetch-square.mjs
              node scripts/fetch-square.mjs --out "${OUTPUT_PATH}"
            fi
          else
            echo "Could not find fetch-square.js. Update the workflow to point to your script path." >&2
            exit 1
          fi

      - name: Show diff
        run: |
          if git diff --quiet -- "${OUTPUT_PATH}"; then
            echo "No changes in ${OUTPUT_PATH}"
          else
            echo "Detected changes in ${OUTPUT_PATH}"
            git --no-pager diff -- "${OUTPUT_PATH}" | tail -n +1 | sed -n '1,120p'
          fi

      - name: Commit & push changes (unless dry run)
        if: ${{ inputs.dry_run != 'true' }}
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore(square): sync items from Square API"
          branch: ${{ github.ref_name }}
          file_pattern: ${{ env.OUTPUT_PATH }}

      - name: Dry run note
        if: ${{ inputs.dry_run == 'true' }}
        run: echo "Dry run selected — not committing changes."
