name: Square → Catalog JSON

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          if npm ci; then
            echo "npm ci OK"
          else
            echo "npm ci failed; refreshing lockfile once"
            npm install --no-audit --no-fund
            npm ci
          fi

- name: Preflight: verify Square token & location
  shell: bash
  run: |
    set -euo pipefail
    echo "Env: $SQUARE_ENVIRONMENT"
    # Show token head/tail + length (no full token in logs)
    tok_len=${#SQUARE_ACCESS_TOKEN}
    echo "Token head: ${SQUARE_ACCESS_TOKEN:0:6}…${SQUARE_ACCESS_TOKEN: -4} (len=$tok_len)"
    echo "Location: $SQUARE_LOCATION_ID"

    # Hit /v2/locations directly against PRODUCTION host if env=production, else sandbox
    if [ "${SQUARE_ENVIRONMENT,,}" = "production" ]; then
      base="https://connect.squareup.com"
    else
      base="https://connect.squareupsandbox.com"
    fi

    echo "GET $base/v2/locations"
    resp="$(curl -sS -w '\n%{http_code}' "$base/v2/locations" \
      -H "Authorization: Bearer $SQUARE_ACCESS_TOKEN" \
      -H "Content-Type: application/json")"

    body="$(echo "$resp" | sed '$d')"
    code="$(echo "$resp" | tail -n1)"
    echo "HTTP $code"
    echo "$body" | head -c 1200; echo

    if [ "$code" != "200" ]; then
      echo "❌ Token rejected by $base. Check that the token is from the SAME environment you're calling and has Catalog/Locations scope."
      exit 1
    fi

    # Check that your LOCATION_ID is among returned locations
    if ! echo "$body" | grep -q "\"id\" *: *\"$SQUARE_LOCATION_ID\""; then
      echo "❌ Location $SQUARE_LOCATION_ID not found for this token. Use a Location ID from the SAME account & environment as the token."
      echo "Tip: copy a Production Location ID from Seller Dashboard → Locations."
      exit 1
    fi

    echo "✅ Token & Location match this environment."
  env:
    SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}
    SQUARE_LOCATION_ID:  ${{ secrets.SQUARE_LOCATION_ID }}
    SQUARE_ENVIRONMENT:  ${{ vars.SQUARE_ENVIRONMENT || 'production' }}


      - name: Run Square sync
        run: npm run sync:square
        env:
          SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}
          SQUARE_LOCATION_ID:  ${{ secrets.SQUARE_LOCATION_ID }}
          SQUARE_ENVIRONMENT:  ${{ vars.SQUARE_ENVIRONMENT || 'production' }}
          OUTPUT_PATH:         data/products.json

      - name: Commit & push if changed
        run: |
          if ! git diff --quiet --exit-code data/products.json package-lock.json; then
            git config user.name  "square-sync[bot]"
            git config user.email "square-sync[bot]@users.noreply.github.com"
            git add data/products.json package-lock.json
            git commit -m "Square sync: refresh catalog JSON"
            git push
          else
            echo "No changes."
          fi
