name: Sync Square Catalog

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes
  workflow_dispatch:         # adds the "Run workflow" button in Actions

permissions:
  contents: write

concurrency:
  group: square-sync
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Future-proof: use npm cache ONLY if a lockfile exists ---
      - name: Setup Node (cached)
        if: ${{ hashFiles('package-lock.json') != '' || hashFiles('npm-shrinkwrap.json') != '' || hashFiles('yarn.lock') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # --- Easy fix: no cache path when lockfile is missing ---
      - name: Setup Node (no cache)
        if: ${{ hashFiles('package-lock.json') == '' && hashFiles('npm-shrinkwrap.json') == '' && hashFiles('yarn.lock') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install deps: ci if lockfile present, else plain install
      - name: Install deps
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          else
            npm i --no-audit --no-fund
          fi

      - name: Run sync
        env:
          SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}
          SQUARE_ENV: ${{ secrets.SQUARE_ENV || 'production' }}
          SQUARE_LOCATION_ID: ${{ secrets.SQUARE_LOCATION_ID }}
        run: npm run sync:square

      # ---- If your site is served from /docs, UNCOMMENT this block ----
      # - name: Move products.json to docs
      #   run: |
      #     mkdir -p docs/data
      #     cp -f data/products.json docs/data/products.json

      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git config user.name "square-sync-bot"
            git config user.email "action@github.com"
            git add -A
            git commit -m "chore: update products.json from Square"
            git push
          else
            echo "No changes."
          fi
