name: Square Sync

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run without committing changes"
        required: false
        default: "false"
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours

permissions:
  contents: write   # needed to push updates back to the repo

concurrency:
  group: square-sync-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      # Required secrets/vars (set these in repo Settings → Secrets and variables → Actions)
      SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}
      SQUARE_ENVIRONMENT: ${{ vars.SQUARE_ENVIRONMENT || 'production' }}
      SQUARE_LOCATION_ID: ${{ vars.SQUARE_LOCATION_ID }}
      # Optional: override output path
      OUTPUT_PATH: data/square-items.json

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: |
          if [ -f package-lock.json ] || [ -f package.json ]; then
            npm ci || npm install
          fi

      - name: Ensure output folder exists
        run: |
          mkdir -p "$(dirname "${OUTPUT_PATH}")"

      - name: Run Square fetch script (ESM/CJS-compatible)
        run: |
          # If your script is CommonJS but repo has "type": "module", Node may error on require().
          # We copy to .mjs and run as ESM to be safe.
          if [ -f "fetch-square.js" ]; then
            cp fetch-square.js fetch-square.mjs
            node fetch-square.mjs --out "${OUTPUT_PATH}"
          elif [ -f "scripts/fetch-square.js" ]; then
            cp scripts/fetch-square.js scripts/fetch-square.mjs
            node scripts/fetch-square.mjs --out "${OUTPUT_PATH}"
          else
            echo "Could not find fetch-square.js. Update the workflow to point to your script path." >&2
            exit 1
          fi

      - name: Show diff
        run: |
          git status --porcelain
          if git diff --quiet -- "${OUTPUT_PATH}"; then
            echo "No changes in ${OUTPUT_PATH}"
          else
            echo "Detected changes in ${OUTPUT_PATH}"
          fi

      - name: Commit & push changes (unless dry run)
        if: ${{ inputs.dry_run != 'true' }}
        uses: stefanzweifel/git-auto-commit@v6
        with:
          commit_message: "chore(square): sync items from Square API"
          branch: ${{ github.ref_name }}
          file_pattern: ${{ env.OUTPUT_PATH }}

      - name: Dry run note
        if: ${{ inputs.dry_run == 'true' }}
        run: echo "Dry run selected — not committing changes."
